plugins:
  - 'prettier'
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'airbnb-base'
  - 'airbnb-typescript/base'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 'latest'
  project:
    - 'tsconfig.json'
ignorePatterns:
  - dist/
root: true
rules:
  '@typescript-eslint/member-ordering':
    - 'error'
    - 'default':
        memberTypes:
          - 'signature'
          - 'field'
          - 'constructor'
          - 'get'
          - 'set'
          - 'abstract-method'
          - 'method'
        order: 'natural'
  'lines-between-class-members': 'off'
  '@typescript-eslint/lines-between-class-members': 'off'
