env:
  commonjs: true
  node: true
parserOptions:
  project: 'tsconfig.json'
rules:
  'no-underscore-dangle':
    - 'error'
    - 'allow':
        - '_id'
  '@typescript-eslint/naming-convention':
    - 'error'
    - selector: variable
      modifiers: ['destructured']
      format: null
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - 'varsIgnorePattern':
        - '_err'
